### ISSUE TITLE
StreamSocketListener is not a constructo

### ISSUE THREAD

**Issue by wjc1022** [KenRmk/winrt-net#2]
When I try to use it and run a sample.
It telled me 
TypeError: StreamSocketListener is not a constructor
            at Server.listen (../winrt-net-master/jspm_packages/npm/winrt-net@1.0.6/lib/net.js:475:24)

I wander how to deal with it. thank you.

**Comment by MikeKovarik** [comment]
This may sound funny, but are you sure you are running the code in windows app? Because there are a few lines of code like this `if (typeof Windows != 'undefined') {var StreamSocketListener = Windows.Networking.Sockets.StreamSocketListener}`.

Anyway, this repo and module is more or less deprecated. I moved and refines the code here [uwp-socket](https://github.com/MikeKovarik/uwp-socket) where I'm refining it for use with bluetooth and serial communication as well. Work in progress though, not enough free time.

**Comment by wjc1022** [comment]
Thank you for your reply.
I have run the app on NodeJS.
It sounds like that I used it in a wrong way?
What I want to do is to let a NodeJS server handle the streamsocket from
uwp app.
Could you please tell me if I have some misunderstanding with the usage.
I'll also check the uwp-socke.

Best Wishes.

2018-05-31 19:24 GMT+09:00 Mike <notifications@github.com>:
